// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`
// Run `bun run cf-typegen` after adding new bindings to wrangler.jsonc

interface CloudflareBindings {
    DB: D1Database;
    ASSETS: Fetcher;
    IMAGEKIT_PUBLIC_KEY: string;
    IMAGEKIT_PRIVATE_KEY: string;
    IMAGEKIT_URL_ENDPOINT: string;
}
